version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
  frontend:
    build:
      context: ./frontend
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
